/**
 * GulfHive ERP - Time, Attendance & Timesheet PDF & Export Service
 * Generates authoritative, clean A4 PDF reports and CSV exports.
 */

import PDFDocument from 'pdfkit';

export interface DailyAttendanceReportRow {
  employeeNumber: string;
  employeeName: string;
  departmentName?: string;
  shiftCode?: string;
  firstIn?: string;
  lastOut?: string;
  workedFormatted: string;
  status: string;
  lateMinutes?: number;
  otMinutes?: number;
}

export interface MonthlyAttendanceSummaryRow {
  employeeNumber: string;
  employeeName: string;
  scheduledDays: number;
  presentDays: number;
  absentDays: number;
  restDays: number;
  holidayDays: number;
  leaveDays: number;
  workedHours: string;
  lateMinutes: number;
  otMinutes: number;
}

export class TimeExportService {
  /**
   * Generate Daily Attendance Summary PDF
   */
  public async generateDailyReportPDF(params: {
    companyName: string;
    workDate: string;
    rows: DailyAttendanceReportRow[];
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 40 });
        const buffers: Buffer[] = [];

        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', (err) => reject(err));

        // Header
        doc.rect(40, 40, doc.page.width - 80, 50).fill('#0F172A');
        doc.fillColor('#FFFFFF').fontSize(14).font('Helvetica-Bold').text(params.companyName.toUpperCase(), 55, 52);
        doc.fontSize(10).font('Helvetica').fillColor('#94A3B8').text(`DAILY ATTENDANCE AUDIT REPORT — DATE: ${params.workDate}`, 55, 68);

        // Summary Stats
        const total = params.rows.length;
        const present = params.rows.filter(r => r.status === 'PRESENT' || r.status === 'LATE').length;
        const absent = params.rows.filter(r => r.status === 'ABSENT').length;
        const late = params.rows.filter(r => r.status === 'LATE' || (r.lateMinutes || 0) > 0).length;

        let y = 105;
        doc.fillColor('#334155').fontSize(9).text(`Total Scheduled: ${total}   |   Present: ${present}   |   Absent: ${absent}   |   Late Arrivals: ${late}`, 45, y);

        // Table Header
        y = 125;
        doc.rect(40, y, doc.page.width - 80, 20).fill('#F1F5F9');
        doc.fillColor('#475569').fontSize(8);
        doc.text('EMP NO', 45, y + 6, { width: 55 });
        doc.text('EMPLOYEE NAME', 105, y + 6, { width: 140 });
        doc.text('SHIFT', 250, y + 6, { width: 50 });
        doc.text('IN', 305, y + 6, { width: 45 });
        doc.text('OUT', 355, y + 6, { width: 45 });
        doc.text('WORKED', 405, y + 6, { width: 50 });
        doc.text('STATUS', 460, y + 6, { width: 60 });
        doc.text('LATE', 525, y + 6, { width: 35 });

        y += 24;
        for (const row of params.rows) {
          if (y > doc.page.height - 60) {
            doc.addPage();
            y = 40;
          }

          doc.fillColor('#1E293B').fontSize(8);
          doc.text(row.employeeNumber, 45, y, { width: 55 });
          doc.text(row.employeeName, 105, y, { width: 140 });
          doc.text(row.shiftCode || '-', 250, y, { width: 50 });
          doc.text(row.firstIn || '-', 305, y, { width: 45 });
          doc.text(row.lastOut || '-', 355, y, { width: 45 });
          doc.text(row.workedFormatted, 405, y, { width: 50 });
          doc.text(row.status, 460, y, { width: 60 });
          doc.text(row.lateMinutes ? `${row.lateMinutes}m` : '-', 525, y, { width: 35 });

          y += 18;
          doc.moveTo(40, y - 4).lineTo(doc.page.width - 40, y - 4).strokeColor('#E2E8F0').lineWidth(0.5).stroke();
        }

        // Footer
        doc.fillColor('#94A3B8').fontSize(7).text(`Generated by GulfHive Authoritative Time System — ${new Date().toISOString()}`, 40, doc.page.height - 30, { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generate CSV format for Daily Attendance
   */
  public generateDailyReportCSV(rows: DailyAttendanceReportRow[]): string {
    const headers = ['Employee Code', 'Employee Name', 'Shift', 'First In', 'Last Out', 'Worked Duration', 'Status', 'Late Minutes', 'OT Minutes'];
    const lines = [headers.join(',')];

    for (const r of rows) {
      lines.push([
        `"${r.employeeNumber}"`,
        `"${r.employeeName}"`,
        `"${r.shiftCode || ''}"`,
        `"${r.firstIn || ''}"`,
        `"${r.lastOut || ''}"`,
        `"${r.workedFormatted}"`,
        `"${r.status}"`,
        r.lateMinutes || 0,
        r.otMinutes || 0,
      ].join(','));
    }

    return lines.join('\n');
  }

  /**
   * Generate CSV format for Monthly Summary
   */
  public generateMonthlySummaryCSV(rows: MonthlyAttendanceSummaryRow[]): string {
    const headers = ['Employee Code', 'Employee Name', 'Scheduled Days', 'Present Days', 'Absent Days', 'Rest Days', 'Holiday Days', 'Leave Days', 'Worked Hours', 'Late Minutes', 'OT Minutes'];
    const lines = [headers.join(',')];

    for (const r of rows) {
      lines.push([
        `"${r.employeeNumber}"`,
        `"${r.employeeName}"`,
        r.scheduledDays,
        r.presentDays,
        r.absentDays,
        r.restDays,
        r.holidayDays,
        r.leaveDays,
        `"${r.workedHours}"`,
        r.lateMinutes,
        r.otMinutes,
      ].join(','));
    }

    return lines.join('\n');
  }
}

export const timeExportService = new TimeExportService();
