/**
 * GulfHive ERP - Modular Monolith Module Manifest
 * Defines explicit boundaries, dependencies, events, and export contracts.
 */

export interface ModuleManifest {
  readonly id: string;
  readonly code: string;
  readonly nameEn: string;
  readonly nameAr: string;
  readonly descriptionEn: string;
  readonly descriptionAr: string;
  readonly version: string;
  readonly dependencies: string[];
  readonly publishedEvents: string[];
  readonly subscribedEvents: string[];
  readonly isCore: boolean;
}

export const GULFHIVE_MODULES: Record<string, ModuleManifest> = {
  people: {
    id: 'mod_people',
    code: 'People',
    nameEn: 'People',
    nameAr: 'الموظفون',
    descriptionEn: 'Employee Master authoritative record, contracts, and employment lifecycle.',
    descriptionAr: 'السجل الرئيسي للموظفين، العقود، ودورة العمل الوظيفية.',
    version: '1.0.0',
    dependencies: [],
    publishedEvents: ['EmployeeCreated', 'EmployeeStatusChanged', 'ContractUpdated'],
    subscribedEvents: [],
    isCore: true,
  },
  time: {
    id: 'mod_time',
    code: 'Time',
    nameEn: 'Time',
    nameAr: 'الوقت',
    descriptionEn: 'Attendance tracking, shift rosters, overtime, and leave management.',
    descriptionAr: 'تتبع الحضور والانصراف، جداول المناوبات، الساعات الإضافية، والإجازات.',
    version: '1.0.0',
    dependencies: ['people'],
    publishedEvents: ['AttendanceLogged', 'LeaveApproved', 'OvertimeCalculated'],
    subscribedEvents: ['EmployeeStatusChanged'],
    isCore: true,
  },
  payroll: {
    id: 'mod_payroll',
    code: 'Payroll',
    nameEn: 'Payroll',
    nameAr: 'الرواتب',
    descriptionEn: 'Deterministic auditable payroll pipeline, WPS file generation, and salary slips.',
    descriptionAr: 'احتساب الرواتب التراكمي الموثق، ملفات حماية الأجور، ومسيرات الرواتب.',
    version: '1.0.0',
    dependencies: ['people', 'time', 'compliance'],
    publishedEvents: ['PayrollCalculated', 'PayrollApproved', 'WpsFileGenerated'],
    subscribedEvents: ['AttendanceLogged', 'LeaveApproved'],
    isCore: true,
  },
  projects: {
    id: 'mod_projects',
    code: 'Projects',
    nameEn: 'Projects',
    nameAr: 'المشاريع',
    descriptionEn: 'Workforce deployment across clients, sites, shifts, and contracts.',
    descriptionAr: 'إدارة تشغيل القوى العاملة عبر العملاء، المواقع، المناوبات، والعقود.',
    version: '1.0.0',
    dependencies: ['people'],
    publishedEvents: ['WorkerDeployed', 'WorkerTransferred', 'DeploymentEnded'],
    subscribedEvents: ['EmployeeStatusChanged'],
    isCore: false,
  },
  sales: {
    id: 'mod_sales',
    code: 'Sales',
    nameEn: 'Sales',
    nameAr: 'المبيعات',
    descriptionEn: 'Customer accounts, quotation pipeline, invoicing, and accounts receivable.',
    descriptionAr: 'حسابات العملاء، عروض الأسعار، الفواتير، وحسابات المدينين.',
    version: '1.0.0',
    dependencies: ['finance'],
    publishedEvents: ['SalesInvoiceIssued', 'CustomerPaymentReceived'],
    subscribedEvents: [],
    isCore: false,
  },
  purchase: {
    id: 'mod_purchase',
    code: 'Purchase',
    nameEn: 'Purchase',
    nameAr: 'المشتريات',
    descriptionEn: 'Vendor master, purchase orders, goods receipts, and accounts payable.',
    descriptionAr: 'سجل الموردين، أوامر الشراء، استلام البضائع، وحسابات الدائنين.',
    version: '1.0.0',
    dependencies: ['finance', 'stock'],
    publishedEvents: ['PurchaseOrderApproved', 'SupplierInvoicePosted'],
    subscribedEvents: [],
    isCore: false,
  },
  stock: {
    id: 'mod_stock',
    code: 'Stock',
    nameEn: 'Stock',
    nameAr: 'المخزون',
    descriptionEn: 'Stock movements ledger, multi-warehouse valuation, and batch tracking.',
    descriptionAr: 'حركات المخزون، تقييم المستودعات المتعددة، وتتبع الشحنات.',
    version: '1.0.0',
    dependencies: [],
    publishedEvents: ['StockMovementRecorded', 'StockThresholdReached'],
    subscribedEvents: ['PurchaseOrderApproved'],
    isCore: false,
  },
  finance: {
    id: 'mod_finance',
    code: 'Finance',
    nameEn: 'Finance',
    nameAr: 'المالية',
    descriptionEn: 'Double-entry general ledger, chart of accounts, and financial statements.',
    descriptionAr: 'دفتر الأستاذ العام بالقيد المزدوج، شجرة الحسابات، والقوائم المالية.',
    version: '1.0.0',
    dependencies: [],
    publishedEvents: ['JournalEntryPosted', 'FiscalPeriodClosed'],
    subscribedEvents: ['PayrollApproved', 'SalesInvoiceIssued', 'SupplierInvoicePosted'],
    isCore: true,
  },
  compliance: {
    id: 'mod_compliance',
    code: 'Compliance',
    nameEn: 'Compliance',
    nameAr: 'الامتثال',
    descriptionEn: 'Versioned GCC statutory rules (GOSI, Labor Laws, Indemnity formulas).',
    descriptionAr: 'محرك القواعد واللوائح التنظيمية لدول مجلس التعاون الخليجي.',
    version: '1.0.0',
    dependencies: [],
    publishedEvents: ['ComplianceRuleEnacted', 'ComplianceRuleDeprecated'],
    subscribedEvents: [],
    isCore: true,
  },
  documents: {
    id: 'mod_documents',
    code: 'Documents',
    nameEn: 'Documents',
    nameAr: 'المستندات',
    descriptionEn: 'Centralized document repository with expiry monitoring and alerts.',
    descriptionAr: 'أرشيف المستندات المركزي ومراقبة صلاحية الإقامات والتراخيص.',
    version: '1.0.0',
    dependencies: [],
    publishedEvents: ['DocumentExpired', 'ExpiryWarningEmitted'],
    subscribedEvents: ['EmployeeCreated'],
    isCore: true,
  },
  reports: {
    id: 'mod_reports',
    code: 'Reports',
    nameEn: 'Reports',
    nameAr: 'التقارير',
    descriptionEn: 'Official PDF, Excel (XLSX), and Word (DOCX) document generation engine.',
    descriptionAr: 'محرك تقارير المؤسسات الاحترافي للمستندات والجداول.',
    version: '1.0.0',
    dependencies: [],
    publishedEvents: ['ReportGenerated'],
    subscribedEvents: [],
    isCore: true,
  },
  settings: {
    id: 'mod_settings',
    code: 'Settings',
    nameEn: 'Settings',
    nameAr: 'الإعدادات',
    descriptionEn: 'Tenant profile, multi-currency settings, role permissions, and audit logs.',
    descriptionAr: 'بيانات المنشأة، إعدادات العملات، الصلاحيات، وسجلات التدقيق.',
    version: '1.0.0',
    dependencies: [],
    publishedEvents: ['TenantConfigUpdated'],
    subscribedEvents: [],
    isCore: true,
  },
};
